# Docker Compose file for Chat-bot
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#      Start app: docker-compose up app{{#fluent}}{{^db.is_sqlite}}
# Start database: docker-compose up db
# Run migrations: docker-compose run migrate{{/db.is_sqlite}}{{/fluent}}
#       Stop all: docker-compose down{{#fluent}}{{^db.is_sqlite}} (add -v to wipe db){{/db.is_sqlite}}{{/fluent}}
